export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIE = "GET_COUNTRIE";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const ORDER_COUNTRIES = "ORDER_COUNTRIES";
export const POST_ACTIVITIE = "POST_ACTIVITIE";
export const FILTER_ACTIVITIES = "FILTER_ACTIVITIES";